# Generated by Django 4.0.6 on 2022-09-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librayapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
